---
name: "test action"
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v3

    - name: Install Nhost CLI
      id: install-nhost-cli
      uses: nhost-actions/install-nhost-cli@v1

    - name: Authenticate with Nhost
      uses: ./
      with:
        pat: some-fake-pat

    - name: verify
      run: |
        cat ~/.nhost/state/auth.json
      shell: bash
